config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :lessons, only: [:index, :show] do
    get :sign, on: :member
    patch :sign_done, on: :member
    delete :sign_out_done, on: :member
    get :my, on: :collection
    get :past, on: :collection
  end
  resources :teachers, only: [:index, :show]
  resources :groups, only: [:index, :show]
  get 'welcome/index'

  namespace :admin do
    resources :lessons do
      get :sign, on: :member
      get :index_all, on: :collection
      patch :sign_done, on: :member
      delete :sign_out_done, on: :member
      patch :student_present, on: :member
      delete :student_not_present, on: :member
    end
    resources :teachers
    resources :groups
    resources :students
    resources :rooms
    get 'welcome/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::BaseController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/welcome/index.html.erb
<h1>Меню администратора</h1>
<br>
<%= link_to 'Занятия', admin_lessons_path %>
<br>
<%= link_to 'Преподаватели', admin_teachers_path %>
<br>
<%= link_to 'Группы', admin_groups_path %>
<br>
<%= link_to 'Ученики', admin_students_path %>
<br>
<%= link_to 'Залы', admin_rooms_path %>