config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :lessons, only: [:index, :show] do
    get :sign, on: :member
    patch :sign_done, on: :member
    delete :sign_out_done, on: :member
    get :my, on: :collection
    get :past, on: :collection
  end
  resources :teachers, only: [:index, :show]
  resources :groups, only: [:index, :show]
  get 'welcome/index'

  namespace :admin do
    resources :lessons do
      get :sign, on: :member
      get :index_all, on: :collection
      patch :sign_done, on: :member
      delete :sign_out_done, on: :member
      patch :student_present, on: :member
      delete :student_not_present, on: :member
    end
    resources :teachers
    resources :groups
    resources :students
    resources :rooms
    get 'welcome/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user, optional: true
  has_many :students_lessons
  has_many :lessons, through: :students_lessons

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :email, with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates :email, uniqueness: true

  scope :by_last_name, -> { order(:last_name) }

  def self.search(term)
    if term
      term.capitalize!
      where('last_name LIKE ?', "%#{term}%")
    else
      all
    end
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    term = params[:term]
    @students = Student.search(term).order(:last_name).page(params[:page])
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to admin_student_path(@student), notice: 'Ученик создан.'
    else
      render :new
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:email, :first_name, :last_name)
  end
end

app/views/admin/students/_form.html.erb
<%= form_for [:admin, @student] do |f| %>
  <%= render 'common/errors', resource: @student %>

  <div class="field">
    <%= f.label :email, "Адрес электронной почты" %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :last_name, "Фамилия" %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :first_name, "Имя" %>
    <%= f.text_field :first_name %>
  </div>

  <div class="actions">
    <%= f.submit "#{@student.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/admin/students/_student.html.erb
<tr><%= render partial: 'admin/students/student_item', locals: {student: student } %></tr>

app/views/admin/students/_student_item.html.erb
<td> <%= link_to student.last_name, admin_student_path(student) %></td>
<td> <%= link_to student.first_name, admin_student_path(student)  %></td>

app/views/admin/students/_student_sign.html.erb
  <td>   
    <%= form_tag(sign_done_admin_lesson_path, method: :patch, data: { confirm: 'Подтверждаете запись?' }) do %>
      <%= hidden_field_tag :student_id, student.id %>
      <%= submit_tag 'Записать', class: "btn btn-default" %>
    <% end %> 
   </td>

app/views/admin/students/_student_sign_out.html.erb
  <td>   
    <%= form_tag(sign_out_done_admin_lesson_path, method: :delete, data: { confirm: 'Подтверждаете отмену записи?' }) do %>
      <%= hidden_field_tag :student_id, student.id %>
      <%= submit_tag 'Отменить запись', class: "btn btn-default" %>
    <% end %> 
   </td>

app/views/admin/students/edit.html.erb
<h1>Редактировать ученика</h1>

<%= render 'form', student: @student %>

<%= link_to 'Назад', admin_student_path(@student) %>

app/views/admin/students/index.html.erb
<h1>Ученики</h1>
  <h3>Поиск</h3>
  <br>
  <%= form_tag(admin_students_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag 'Искать' %>
  <% end %>
  Введите фамилию ученика

<table class= "table table-striped">
  <thead>
    <tr>
      <th>Фамилия</th>
      <th>Имя</th>
    </tr>
  </thead>

  <tbody>
    <%= render @students  %>
  </tbody>
</table>

<br>
<%= paginate @students %>
<br>
<%= link_to 'Новый ученик', new_admin_student_path %>
<br>
<%= link_to 'Основное меню', admin_welcome_index_path %>

app/views/admin/students/new.html.erb
<h1>Новый ученик</h1>

<%= render 'form', student: @student %>

<%= link_to 'Назад', admin_students_path %>

app/views/admin/students/show.html.erb
<h2>Ученик</h2>
  <br>
  <strong>
    <%= @student.first_name %>
    <%= @student.last_name %>
   <br>
  <%=@student.email%>
  </strong>
  <br>
  <br>
  <table class= "table table-striped">
    <thead>
    <tr>
      <th>Записан на занятия</th>
    </tr>
  </thead>
    <%= render partial: 'lessons/lesson', collection: @student.lessons, as: :lesson %>
  </table>
  <br>
  <br>
<%= link_to 'Назад', admin_students_path %>