config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :lessons, only: [:index, :show] do
    get :sign, on: :member
    patch :sign_done, on: :member
    delete :sign_out_done, on: :member
    get :my, on: :collection
    get :past, on: :collection
  end
  resources :teachers, only: [:index, :show]
  resources :groups, only: [:index, :show]
  get 'welcome/index'

  namespace :admin do
    resources :lessons do
      get :sign, on: :member
      get :index_all, on: :collection
      patch :sign_done, on: :member
      delete :sign_out_done, on: :member
      patch :student_present, on: :member
      delete :student_not_present, on: :member
    end
    resources :teachers
    resources :groups
    resources :students
    resources :rooms
    get 'welcome/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :room
  has_many :lessons_teachers
  has_many :teachers, through: :lessons_teachers
  has_many :students_lessons
  has_many :students, through: :students_lessons

  scope :by_time, -> { order(:start_time) }
  before_validation :set_end_time

  validate :validate_room_time
  validate :validate_teacher_time
  validates :teachers, presence: true
  validates :style, presence: true
  validates :start_time, presence: true
  validates :duration, presence: true, numericality: { greater_than: 0 }
  validates :end_time, presence: true

  def sign_done(student, by_admin = false)
    students << student
    student_lesson = find_students_lessons(student)
    student_lesson.sign_by_admin = by_admin
    student_lesson.save
  end

  def sign_out_done(student)
    students.delete(student)
  end

  def student_present?(student)
    find_students_lessons(student)
  end

  def lesson_students_status(studs = students)
    @list = {}
    studs.by_last_name.each do |stud|
      sl = find_students_lessons(stud)
      @list[stud] = sl
    end
    @list
  end

  def student_presence(sl, val)
    sl.presence = val
    sl.save
  end

  def self.relevant_lessons(weeks_before, weeks_after)
    lessons = []
    current_week = Time.now.strftime('%W').to_i
    range = (current_week - weeks_before)..(current_week + weeks_after)
    Lesson.find_each { |lesson| lessons << lesson if range.include?(lesson.start_time.strftime('%W').to_i) }
    sort_by_time(lessons)
  end

  def self.sort_by_time(lessons)
    lessons_sorted = []
    time_lessons = {}
    lessons.each { |lesson| time_lessons[lesson.start_time] = lesson }
    lessons_time = time_lessons.sort
    lessons_time.each { |_time, lesson| lessons_sorted << lesson }
    lessons_sorted
  end

  private

  def lessons_cross
    cross = []
    Lesson.where('end_time > ?', Time.now).find_each do |lesson|
      cross << lesson if lesson.start_time.between?(start_time, end_time) ||
                         lesson.end_time.between?(start_time, end_time)
    end
    cross.delete(self)
    cross
  end

  def lessons_cross_memo
    @cross ||= lessons_cross
  end

  def validate_room_time
    lessons_cross_memo.each { |lesson| errors.add(:base, 'Время проведения пересекается с другими занятиями в этом зале') if lesson.room == room }
  end

  def validate_teacher_time
    lessons_cross_memo.each { |lesson| errors.add(:base, 'Преподаватель уже ведет занятие в это время') if lesson.teachers & teachers }
  end

  def set_end_time
    self.duration ||= 0
    self.end_time = start_time + self.duration * 60
  end

  def find_students_lessons(student)
    students_lessons.where(student_id: student.id, lesson_id: id).first
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::BaseController
  before_action :set_lesson, except: [:index, :index_all, :new, :create]

  def index
    @lessons = Lesson.relevant_lessons(1, 2)
  end

  def index_all
    @lessons = Lesson.order(:start_time).page(params[:page])
    @pagination = true
    render :index
  end

  def new
    @lesson = Lesson.new
    @lesson.start_time = Time.now.strftime('%F %R')
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to admin_lesson_path(@lesson), notice: 'Урок создан.'
    else
      render :new
    end
  end

  def show
    @list = @lesson.lesson_students_status
  end

  def edit
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to admin_lesson_path(@lesson), notice: 'Урок изменен.'
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to admin_lessons_path, notice: 'Урок удален.'
  end

  def sign
    term = params[:term]
    @students = Student.search(term).order(:last_name).page(params[:page])
    @list = @lesson.lesson_students_status(@students)
  end

  def sign_done
    student = Student.find(params[:student_id])
    @lesson.sign_done(student, true)
    redirect_to sign_admin_lesson_path(@lesson)
  end

  def sign_out_done
    student = Student.find(params[:student_id])
    @lesson.sign_out_done(student)
    redirect_to sign_admin_lesson_path(@lesson)
  end

  def student_present
    student_lesson = StudentsLesson.find(params[:student_lesson_id])
    @lesson.student_presence(student_lesson, true)
    redirect_to admin_lesson_path(@lesson)
  end

  def student_not_present
    student_lesson = StudentsLesson.find(params[:student_lesson_id])
    @lesson.student_presence(student_lesson, false)
    redirect_to admin_lesson_path(@lesson)
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:style, :start_time, :duration, :group_id, :room_id, teacher_ids: [])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :sign, :sign_done, :sign_out, :sign_out_done]
  before_action :authenticate_user!, only: [:sign, :sign_done, :sign_out, :sign_out_done]

  def index
    @lessons = Lesson.relevant_lessons(0, 1)
  end

  def show
  end

  def sign
    @presence = @lesson.student_present?(current_user.student)
  end

  def sign_done
    @lesson.sign_done(current_user.student)
    redirect_to sign_lesson_path(@lesson)
  end

  def sign_out_done
    @lesson.sign_out_done(current_user.student)
    redirect_to sign_lesson_path(@lesson)
  end

  def my
    @lessons = current_user.student.lessons.where('end_time > ?', Time.now).order(:start_time)
  end

  def past
    @lessons = current_user.student.lessons.where('end_time < ?', Time.now).order(:start_time)
    render :my
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_head.html.erb
  <th> Занятие </th>
  <th> Группа </th>
  <th> Преподаватель </th>
  <th> Зал </th>  
  <th> Дата и время </th>
  <th> Длительность </th>

app/views/lessons/_lesson.html.erb
  <td><%= link_to lesson.style, lesson %></td>
  <% if lesson.group %>
  	<td><%= link_to lesson.group.title, lesson.group %></td>
  <%end%>	
  <td><%= render partial: 'teachers/teacher_item', collection: lesson.teachers, as: :teacher %></td>
  <td><%= lesson.room.title %></td> 
  <td><%= lesson.start_time.strftime("%F %T") %></td>
  <td><%= lesson.duration %></td>
  

app/views/lessons/_lesson_item.html.erb
<tr>
  <td><%= link_to lesson.style, lesson %></td>
  <td><%= link_to lesson.group.title, lesson.group %></td>
  <td><%= lesson.start_time %></td>
</tr>

app/views/lessons/_show.html.erb
<strong>Направление:</strong>
  <%= @lesson.style %>
</p>
  
<p>
  <strong>Группа:</strong>
  <% if @lesson.group.present? %>
    <%= @lesson.group.title %>
  <% else%>
    Не регулярное.
  <% end %>
</p>

Преподаватели:
      <ul>
      <%= render partial: 'teachers/teacher_item', collection: @lesson.teachers, as: :teacher %>
    </ul>
  <br>
Зал:
<%= @lesson.room.title%>
<br> 
Дата и время начала: <%=@lesson.start_time.strftime '%d.%m.%Y %H:%M'%>
   <br> 
Дата и время окончания: <%=@lesson.end_time.strftime '%d.%m.%Y %H:%M'%> 
  <br>
Продолжительность: <%=@lesson.duration%> 

app/views/lessons/index.html.erb
<h1>Занятия</h1>

<table class= "table table-striped">
  <thead>
    <%= render 'head' %>
  </thead>

  <tbody>
    <% @lessons.each do |lesson|%>
      <tr>  
        <%= render lesson %>
        <td><%= link_to 'Запись', sign_lesson_path(lesson)%></td>
      </tr>
    <%end%>
  </tbody>
</table>

<br>

<br>
<%= link_to 'Основное меню', root_path %>

app/views/lessons/my.html.erb
<h1>Ваши занятия</h1>
<%= link_to 'Прошедшие', past_lessons_path %>
<%= link_to 'Будущие', my_lessons_path %>
  <table class= "table table-striped">
    <thead>
      <tr>
        <th>Занятия</th>
      </tr>
    </thead>

    <tbody>
    <tr>
      <th> Урок </th>
      <th> Группа </th>
      <th> Преподаватель </th>
      <th> Дата и время </th>    
    </tr>
    <% @lessons.each do |lesson|%>
      <tr>  
        <%= render lesson %>
      </tr>
    <%end%>  
    </tbody>
  </table>
<br>

<%= link_to 'Основное меню', root_path %>

app/views/lessons/show.html.erb
 <%= render partial: 'lessons/show', object: @lesson  %>

<br>
<%= link_to 'Назад', lessons_path %>

app/views/lessons/sign.html.erb
<%= render partial: 'lessons/show', object: @lesson  %>
<br>
<br>
<% if @presence%>
  <strong>Вы записаны на этот урок</strong>
  <br>
  <br>
  <td><%= form_tag(sign_out_done_lesson_path, method: :delete, data: { confirm: 'Подтверждаете отмену записи?' }) do %>
    <%= submit_tag 'Отменить запись', class: "btn btn-default" %>
  <% end %> 
    </td>
<%else%>
  <td>  <%= form_tag(sign_done_lesson_path, method: :patch, data: { confirm: 'Подтверждаете запись?' }) do %>
    <%= submit_tag 'Записаться', class: "btn btn-default" %>
  <% end %> 
<%end%>
<br>

<%= link_to 'Назад', my_lessons_path %>