config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :lessons, only: [:index, :show] do
    get :sign, on: :member
    patch :sign_done, on: :member
    delete :sign_out_done, on: :member
    get :my, on: :collection
    get :past, on: :collection
  end
  resources :teachers, only: [:index, :show]
  resources :groups, only: [:index, :show]
  get 'welcome/index'

  namespace :admin do
    resources :lessons do
      get :sign, on: :member
      get :index_all, on: :collection
      patch :sign_done, on: :member
      delete :sign_out_done, on: :member
      patch :student_present, on: :member
      delete :student_not_present, on: :member
    end
    resources :teachers
    resources :groups
    resources :students
    resources :rooms
    get 'welcome/index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :lessons
  validates :style, presence: true
  validates :title, presence: true
  scope :by_title, -> { order(:title) }
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to admin_group_path(@group), notice: 'Группа создана.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to admin_group_path(@group), notice: 'Группа изменена.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, notice: 'Группа удалена.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:style, :title)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show]

  def index
    @groups = Group.all
  end

  def show
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end
end

app/views/admin/groups/index.html.erb
<h1>Группы</h1>

<table class= "table table-striped">
  <thead>
    <tr>
      <th>Группы</th>

    </tr>
  </thead>

  <tbody>
    <% @groups.by_title.each do |group|%>
      <tr>  
          <%= render partial: 'groups/group', object: group  %>
          <td><%= link_to 'Редактировать', edit_admin_group_path(group) %> </td>
          <td><%= link_to 'Удалить', [:admin, group], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <%end%>
  </tbody>
</table>

<%= link_to 'Новая группа', new_admin_group_path %>
<br>
<%= link_to 'Основное меню', admin_welcome_index_path %>

app/views/admin/groups/show.html.erb
 <%= render partial: 'groups/show', object: @group  %>

<br>
<%= link_to 'Редактировать', edit_admin_group_path(@group) %> 
<br>
<%= link_to 'Назад', admin_groups_path %>